# Dockerfile.nginx
# Используем официальный образ Nginx
FROM nginx:stable-alpine

# Удаляем стандартную конфигурацию Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Копируем вашу кастомную конфигурацию Nginx
COPY nginx.conf /etc/nginx/conf.d/ytdlp.conf

# Копируем статические файлы фронтенда
# COPY --from=frontend-builder /app/src /usr/share/nginx/html
COPY ./frontend/src/. /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
