version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "${SERVER_PORT:-8080}:8080" # Маппинг порта хоста (по умолчанию 8080) на внутренний порт контейнера 8080
    environment:
      SERVER_PORT: 8080 # Внутренний порт, на котором Spring Boot будет слушать


  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend

